// 端到端测试用例数据。新增用例：在对应模块末尾追加对象，编号取下一个序号。
export const CASES = [
  { id: "SYS-001", mod: "系统与服务", title: "后端健康检查", pri: "P0",
    pre: "后端已启动（e2e_up.py）",
    steps: "1. 请求 GET http://127.0.0.1:8734/api/health\n2. 检查响应体",
    expect: "返回 200；响应体 {\"status\":\"ok\",\"db\":true}；SQLite 连接正常", actual: "" },
  { id: "SYS-002", mod: "系统与服务", title: "SSE 连接与断线重连", pri: "P0",
    pre: "后端已启动，前端页面已打开",
    steps: "1. 打开对话页，观察左上角状态条\n2. 停止后端进程\n3. 观察状态条变化\n4. 重启后端，等待 5 秒",
    expect: "初始显示已连接（绿点）；后端停止后状态条变为连接断开提示；后端恢复后自动重连并显示已连接", actual: "" },
  { id: "SYS-003", mod: "系统与服务", title: "事件信封结构完整性", pri: "P1",
    pre: "SSE 连接正常",
    steps: "1. 通过测试接口发布一条 WARNING 事件\n2. 在前端事件流或原始 SSE 中检查事件格式",
    expect: "事件包含 type/id/ts/data 四个字段；data 为对象；wire 格式为 event: TYPE + data: JSON", actual: "" },
  { id: "CRED-001", mod: "凭据体系", title: "创建凭据且密钥只写不读", pri: "P0",
    pre: "进入设置页",
    steps: "1. 填写 key_id、密钥、标签（如 main-loop）、端点、模型、预算\n2. 点击创建\n3. 查看凭据列表",
    expect: "创建成功；列表显示掩码元数据（key_id/版本/标签/状态/预算），不包含 secret 字段，不出现明文密钥", actual: "" },
  { id: "CRED-002", mod: "凭据体系", title: "测试连接返回模型三态", pri: "P1",
    pre: "已有有效凭据",
    steps: "1. 在凭据列表点击测试连接\n2. 等待返回",
    expect: "返回 probe 结果：mode 为 native/text/unsupported 之一，附 detail 说明；凭据无效时返回明确错误", actual: "" },
  { id: "CRED-003", mod: "凭据体系", title: "撤销凭据后引用失效", pri: "P1",
    pre: "已有凭据且被某工具引用",
    steps: "1. 在设置页点击撤销\n2. 检查列表状态\n3. 触发引用该 Key 的工具执行",
    expect: "状态变为 revoked；被引用工具执行时报错（引用凭据不可用），不静默失败", actual: "" },
  { id: "CRED-004", mod: "凭据体系", title: "预算耗尽与 scope 收窄", pri: "P2",
    pre: "创建带预算的凭据与带 scope 的凭据",
    steps: "1. 使某凭据预算耗尽\n2. 再次发起需要该能力的请求\n3. 检查带 scope 凭据对其他请求方是否可见",
    expect: "预算耗尽的凭据不再被解析命中；scope 收窄后仅授权请求方可使用", actual: "" },
  { id: "TURN-001", mod: "对话与主循环", title: "发送消息并收到回复", pri: "P0",
    pre: "已配置有效的 main-loop 凭据；对话页已连接",
    steps: "1. 输入一条普通消息并发送\n2. 观察消息流与状态条\n3. 等待回合结束",
    expect: "用户消息上屏；agent 回复上屏；状态条运行指示出现并恢复；无 ERROR 事件", actual: "" },
  { id: "TURN-002", mod: "对话与主循环", title: "工具调用完整链路", pri: "P0",
    pre: "已配置有效凭据；内置工具（echo/now/memory_search）已注册",
    steps: "1. 发送会触发工具调用的消息（如询问时间或检索历史记忆）\n2. 观察工具卡片\n3. 等待回合结束",
    expect: "TOOL_START/TOOL_END 事件按序出现；工具卡片折叠展示名称与结果；工具结果成功回喂模型；无 400 协议错误", actual: "" },
  { id: "TURN-003", mod: "对话与主循环", title: "无凭据时的优雅降级", pri: "P1",
    pre: "未配置 main-loop 凭据",
    steps: "1. 发送消息\n2. 观察状态条与事件流",
    expect: "发出 WARNING 事件提示未配置凭据；前端显示提示但不崩溃；不产生假回复", actual: "" },
  { id: "TURN-004", mod: "对话与主循环", title: "迭代预算终止循环", pri: "P2",
    pre: "构造会持续调用工具的模型行为（如反复调用 echo）",
    steps: "1. 发送触发循环的消息\n2. 观察回合终止",
    expect: "达到迭代上限（native 5 次）后回合以 stopped 终止；USAGE 事件包含迭代次数与 token 用量", actual: "" },
  { id: "MEM-001", mod: "记忆域", title: "对话原文写入记忆", pri: "P1",
    pre: "已进行至少一轮对话",
    steps: "1. 检查数据库 messages 表\n2. 核对消息角色、内容、时间戳",
    expect: "用户与助手消息均以原文写入 messages；绑定正确的 fragment_id；内容与 raw 完整可重放", actual: "" },
  { id: "MEM-002", mod: "记忆域", title: "封块与摘要生成", pri: "P2",
    pre: "同一话题下持续对话",
    steps: "1. 连续对话直至达到封块阈值（默认 30 条消息）\n2. 检查 fragments 表\n3. 检查 memory_index 表",
    expect: "fragment 被关闭（closed_at 非空）；摘要由主模型生成并写入；机械索引生成（关键词/实体/token 估算）", actual: "" },
  { id: "MEM-003", mod: "记忆域", title: "历史记忆检索", pri: "P1",
    pre: "已有若干封块的历史记忆",
    steps: "1. 在对话中询问之前讨论过的内容\n2. 观察模型是否检索历史",
    expect: "模型调用 memory_search 工具；命中结果带来源标记；回复能引用历史内容", actual: "" },
  { id: "KNOW-001", mod: "知识域", title: "低影响知识自动验证生效", pri: "P1",
    pre: "后端运行中",
    steps: "1. 创建一条 general_fact 类知识并提交\n2. 跟踪状态变化\n3. 检查注入面",
    expect: "状态按 draft→pending_review→verified→active 流转；低影响类别系统自动验证；active 后进入注入面", actual: "" },
  { id: "KNOW-002", mod: "知识域", title: "高影响知识需用户确认", pri: "P1",
    pre: "后端运行中",
    steps: "1. 创建 user_profile 或 goal 类知识并提交\n2. 尝试系统自动验证\n3. 用户确认后验证",
    expect: "系统自动验证被拒绝（需 user）；用户确认后进入 verified→active；确认前不进入注入面", actual: "" },
  { id: "KNOW-003", mod: "知识域", title: "supersedes 版本链", pri: "P2",
    pre: "已有 active 知识条目",
    steps: "1. 创建新版本并指定 supersedes_id\n2. 验证并激活新版本\n3. 检查旧版本状态与历史链",
    expect: "新版本激活后旧版本自动 revoked；history 链按旧→新完整可查", actual: "" },
  { id: "GRAPH-001", mod: "图导航", title: "话题创建与星球位置惰性", pri: "P0",
    pre: "后端运行中；对话页可用",
    steps: "1. 创建新话题（首次对话自动创建或通过对话触发）\n2. 打开话题星球\n3. 关闭后再次打开",
    expect: "新话题在星球上出现地点；两次打开位置一致（位置惰性，不重排）；坐标持久化于 nodes.meta", actual: "" },
  { id: "GRAPH-002", mod: "图导航", title: "话题聚焦与详情加载", pri: "P0",
    pre: "星球页已打开且存在多个话题",
    steps: "1. 点击话题列表项或星球地点\n2. 观察相机运动与右侧面板",
    expect: "相机自动旋转聚焦到目标地点；详情面板加载片段列表、实体标记、知识条目", actual: "" },
  { id: "GRAPH-003", mod: "图导航", title: "从这里开始（片段偏置）", pri: "P1",
    pre: "星球页已打开；话题含多个片段",
    steps: "1. 选中一个片段（或不选）\n2. 点击从这里开始\n3. 回到对话页发送消息",
    expect: "星球页关闭回到对话页；锚点更新为所选话题与片段；后续注入对该片段产生注意力偏置（提示词变化）", actual: "" },
  { id: "TOOL-001", mod: "工具机制", title: "工具创建完整流程", pri: "P0",
    pre: "已配置有效凭据；审批可响应",
    steps: "1. 发起工具创建请求\n2. 查看提案解释与工具定义\n3. 查看确定性测试结果\n4. 批准创建（如需凭据再批准授权）\n5. 调用新工具",
    expect: "流程依次通过：提案→测试（全部用例通过）→审批→注册；新工具与原生工具并列；调用返回预期结果", actual: "" },
  { id: "TOOL-002", mod: "工具机制", title: "审批拒绝不注册", pri: "P1",
    pre: "工具创建流程可触发",
    steps: "1. 发起工具创建\n2. 在审批弹窗点击拒绝",
    expect: "工具不注册；明确返回审批拒绝原因；不产生部分注册状态", actual: "" },
  { id: "TOOL-003", mod: "工具机制", title: "交叉测试失败阻断", pri: "P1",
    pre: "可构造输出与断言不符的工具提案",
    steps: "1. 提交代码与测试用例不符的提案\n2. 观察流程",
    expect: "确定性测试失败（断言不匹配）；流程在测试步骤终止；不进入审批与注册", actual: "" },
  { id: "APPROVAL-001", mod: "审批流", title: "三类审批弹窗展示与响应", pri: "P0",
    pre: "后端运行中；对话页已连接",
    steps: "1. 依次触发工具创建、凭据授权、高影响知识三类审批\n2. 检查弹窗内容\n3. 分别批准与拒绝",
    expect: "弹窗显示对应类型标题与 payload（解释/测试摘要/授权对象）；批准与拒绝均回传后端并关闭弹窗；队列串行不堆叠", actual: "" },
  { id: "APPROVAL-002", mod: "审批流", title: "审批超时处理", pri: "P2",
    pre: "审批流程可触发",
    steps: "1. 触发审批但不响应\n2. 等待超时（默认 300 秒，测试可缩短）",
    expect: "超时后按拒绝处理；发起方收到 timeout 结果；无悬挂等待", actual: "" },
  { id: "UI-001", mod: "前端交互", title: "长对话虚拟滚动", pri: "P1",
    pre: "对话页已连接",
    steps: "1. 生成大量消息（100+ 条）\n2. 上下滚动消息流\n3. 发送新消息",
    expect: "滚动流畅无明显卡顿；消息按需渲染；新消息时若处于底部则自动跟随", actual: "" },
  { id: "UI-002", mod: "前端交互", title: "悬浮球与星球过渡", pri: "P0",
    pre: "对话页已连接",
    steps: "1. 点击右下角悬浮球\n2. 等待全屏星球\n3. 点击收起",
    expect: "星球页以过渡动画展开（相机推进）；星球渲染正常（WebGL 可用时显示 fps）；收起后回到对话页", actual: "" },
  { id: "UI-003", mod: "前端交互", title: "记忆强度滑块", pri: "P2",
    pre: "对话页已连接；已有记忆数据",
    steps: "1. 调整记忆强度滑块至 0 与 1\n2. 各发送一条消息\n3. 对比注入内容",
    expect: "滑块值影响注入预算（0 时知识域预算取下限，1 时取上限）；注入内容随强度变化可见", actual: "" },
  { id: "PACK-001", mod: "桌面打包", title: "sidecar 启动与退出清理", pri: "P0",
    pre: "已构建 Tauri 应用（sidecar 已打包）",
    steps: "1. 启动桌面应用\n2. 检查后端健康\n3. 退出应用",
    expect: "应用启动时自动拉起 Python sidecar；后端 health 通过；退出应用时 sidecar 进程被终止，无残留进程", actual: "" },
  { id: "PACK-002", mod: "桌面打包", title: "端口占用容错", pri: "P2",
    pre: "已构建桌面应用",
    steps: "1. 手动占用 8734 端口\n2. 启动应用",
    expect: "应用不崩溃；给出明确错误提示或自动切换端口；可恢复", actual: "" },
];
