/** E1 的页内测量脚本（单引号行数组拼装，避免嵌套模板字面量）。
 * 同一次页面状态内取回：主题、卡片/关系/组、面板状态、失败区文案、可见文本与面板重叠面积。 */
export const METRICS_JS = [
  "(() => {",
  "  const q = (s) => document.querySelector(s);",
  "  const text = (s) => { const el = q(s); if (!el) return null; const raw = el.innerText || el.textContent || \"\"; return raw.split(String.fromCharCode(10)).join(\" \").trim(); };",
  "  const box = (s) => { const el = q(s); if (!el) return null; const b = el.getBoundingClientRect(); return { x: Math.round(b.x), y: Math.round(b.y), w: Math.round(b.width), h: Math.round(b.height) }; };",
  "  const shown = (s) => { const el = q(s); if (!el) return false; const b = el.getBoundingClientRect(); const st = getComputedStyle(el); return b.width > 0 && b.height > 0 && st.visibility !== \"hidden\" && st.display !== \"none\"; };",
  "  const bodyBg = getComputedStyle(document.body).backgroundColor;",
  "  const nums = bodyBg.slice(bodyBg.indexOf(String.fromCharCode(40)) + 1, bodyBg.indexOf(String.fromCharCode(41))).split(\",\").map((v) => parseFloat(v));",
  "  const lin = nums.slice(0, 3).map((v) => { const s = v / 255; return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4); });",
  "  const lum = lin.length === 3 && lin.every((v) => Number.isFinite(v)) ? Number((0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]).toFixed(4)) : null;",
  "  let stored = null; try { stored = localStorage.getItem(\"qio-theme\"); } catch (e) { stored = \"ls-error\"; }",
  "  const out = {",
  "    themeAttr: document.documentElement.getAttribute(\"data-theme\"),",
  "    themeStored: stored,",
  "    bodyBg, bodyLuminance: lum,",
  "    viewport: [window.innerWidth, window.innerHeight],",
  "    cardCount: document.querySelectorAll(\"[data-im=card]\").length,",
  "    linkCount: document.querySelectorAll(\"svg.link-layer line.line\").length,",
  "    linkLabelCount: document.querySelectorAll(\"svg.link-layer text.label\").length,",
  "    groupCount: document.querySelectorAll(\"[data-im=group]\").length,",
  "    toolbarHeight: q(\"[data-im=board-toolbar]\") ? Math.round(q(\"[data-im=board-toolbar]\").getBoundingClientRect().height) : null,",
  "    chatOpen: shown(\"[data-im=chat-panel]\"),",
  "    batchOpen: shown(\"[data-im=batch-list]\"),",
  "    batchItems: document.querySelectorAll(\"[data-im=batch-item]\").length,",
  "    chatBox: box(\"[data-im=chat-panel]\"),",
  "    batchBox: box(\"[data-im=batch-list]\"),",
  "    saveStatusText: text(\"[data-im=submit-save-status]\"),",
  "    submitStatusText: text(\"[data-im=submit-status]\"),",
  "    submitButtonText: text(\"[data-im=submit]\"),",
  "    failureReason: text(\"[data-im=submit-failure-reason]\"),",
  "    failureRetention: text(\"[data-im=submit-failure-retention]\"),",
  "    blockedReason: text(\"[data-im=submit-blocked-reason]\"),",
  "    switchBarText: text(\"[data-im=overlay-switch]\"),",
  "    switchChat: shown(\"[data-im=overlay-switch-chat]\"),",
  "    switchBatch: shown(\"[data-im=overlay-switch-batch]\"),",
  "    visibleText: document.body.innerText.split(String.fromCharCode(10)).join(\" \").slice(0, 4000),",
  "  };",
  "  if (out.chatBox && out.batchBox) {",
  "    const w = Math.max(0, Math.min(out.chatBox.x + out.chatBox.w, out.batchBox.x + out.batchBox.w) - Math.max(out.chatBox.x, out.batchBox.x));",
  "    const h = Math.max(0, Math.min(out.chatBox.y + out.chatBox.h, out.batchBox.y + out.batchBox.h) - Math.max(out.chatBox.y, out.batchBox.y));",
  "    out.overlap = Math.round(w * h);",
  "  } else out.overlap = null;",
  "  return out;",
  "})()",
].join(String.fromCharCode(10));
