"""Knowledge domain: lifecycle state machine, scope resolution, verification, injection."""

from agent.knowledge.inject import InjectionSource
from agent.knowledge.lifecycle import (
    CATEGORIES,
    HIGH_IMPACT_CATEGORIES,
    LOW_IMPACT_CATEGORIES,
    DeactivateOutcome,
    DuplicateActiveChain,
    KnowledgeItem,
    KnowledgeNotFound,
    KnowledgeService,
    KnowledgeState,
    VersionConflict,
    chain_of,
    deactivate_atomic,
    impact_of,
    list_duplicate_active_chains,
    resolve_current,
    revise_atomic,
)
from agent.knowledge.scope import (
    SCOPE_VERSION,
    ScopeResolution,
    attribution_for_new,
    clear_unresolved,
    is_global_node_id,
    is_injectable,
    is_unresolved,
    mark_unresolved,
    resolve_for_item,
    resolve_scope,
    user_global_node_id,
)
from agent.knowledge.verify import VerificationService

__all__ = [
    "KnowledgeItem",
    "KnowledgeService",
    "KnowledgeState",
    "KnowledgeNotFound",
    "VersionConflict",
    "DeactivateOutcome",
    "DuplicateActiveChain",
    "VerificationService",
    "InjectionSource",
    "resolve_current",
    "revise_atomic",
    "deactivate_atomic",
    "chain_of",
    "list_duplicate_active_chains",
    "ScopeResolution",
    "resolve_scope",
    "resolve_for_item",
    "attribution_for_new",
    "is_injectable",
    "is_unresolved",
    "is_global_node_id",
    "user_global_node_id",
    "mark_unresolved",
    "clear_unresolved",
    "SCOPE_VERSION",
    "CATEGORIES",
    "HIGH_IMPACT_CATEGORIES",
    "LOW_IMPACT_CATEGORIES",
    "impact_of",
]
